<a href="https://colab.research.google.com/github/saipriya1910/DAE-Program/blob/main/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [ ]:
arr=np.array([[1,2],[4,5]])
print(arr)

[[1 2]
 [4 5]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)

[ 6  8 10]


In [ ]:
import numpy as np
arr = np.array([[1,4,3],[1,4,3]])
print(arr)

[[1 4 3]
 [1 4 3]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[arr%2==0])

[ 2  4  6  8 10]


In [ ]:
import numpy as np
R=np.zeros((4,5))
print(R)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
A=np.ones((3,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
V=np.random.rand()
print(V)

0.9452238609409517


In [ ]:
import numpy as np
I=np.array((2,4))
print(I)

[2 4]


In [ ]:
import numpy as np
N=np.eye(1,1)
print(N)

[[1.]]


In [ ]:
import numpy as np
D=np.linspace(1,1,1)

print(D)

[1.]


In [ ]:
import numpy as np
R=np.array((1,4,3))
print(R)

[1 4 3]


In [ ]:
import numpy as np
A=np.ones((3,3))
print(A*143)

[[143. 143. 143.]
 [143. 143. 143.]
 [143. 143. 143.]]


In [ ]:
import numpy as np
student_marks=np.array([20,30,40,50])
print("student marks:")
print(student_marks)

student marks:
[20 30 40 50]
